#!/usr/bin/env bash

#OCR_TYPE=x86-mpi CONFIG_NUM_THREADS=9 OCR_NODEFILE="./nodefile16" make uninstall clean run

if [ ! -s "z_ptest_daveReduction.c" ]
then
    echo "ERROR: Missing OCR C code file"
else
    ABSPATH="/lustre/home/dvillen/w/ocr/git2017-3Mar13-testReduction/apps/hll/autogen/examples/ptest_DaveReduction"
    #echo "ABSPATH=$ABSPATH"

    export MACHINE_COUNT=0
    export MACHINE_COUNT=8

    unset OCR_NODEFILE
    if [ $MACHINE_COUNT -eq 4 ]
    then
        export OCR_NODEFILE="$ABSPATH/y_OCRnodefile4"
        export COUNT_FOR_FORKJOIN="$(( 8 * $MACHINE_COUNT))"
    elif [ $MACHINE_COUNT -eq 8 ]
    then
        export OCR_NODEFILE="$ABSPATH/y_OCRnodefile8"
        export COUNT_FOR_FORKJOIN="$(( 8 * $MACHINE_COUNT))"
    fi
    echo "OCR_NODEFILE=$OCR_NODEFILE"
    echo "COUNT_FOR_FORKJOIN=$COUNT_FOR_FORKJOIN"

    export RECURB_ITER_COUNT=1000
    export CONFIG_NUM_THREADS=9
    #export REDUCTION_IMPL='EAGER'
    export OCR_TYPE=x86-mpi

    export APP_CFLAGS="-DCOUNT_FOR_FORKJOIN=$COUNT_FOR_FORKJOIN -DRECURB_ITER_COUNT=$RECURB_ITER_COUNT"
    echo $APP_CFLAGS

    OCR_TYPE=x86-mpi make uninstall clean
    make run > z_log

    rm -f z_output
    grep "INFO:" z_log > z_output
    if [ ! -s "z_output" ]
    then
        echo "ERROR: Missing OCR C code output"
    else
        echo "Data collected in z_output."
    fi
fi

