HPGMG_ARCH = exascale-rocr
HPGMG_CC = gcc
HPGMG_CCLD = g++
HPGMG_CFLAGS = -DRSTREAM_CHEBY -O0 -g -fopenmp -std=c99 -I/home/thenretty/xstack/ocr/install/x86-pthread-x86/include -I/home/thenretty/xstack/ocr/install/x86-pthread-x86/include/extensions -I/opt/reservoir/latest-thenretty/rstream-3.3.3/runtime/codelet/ocr/inc
HPGMG_CPPFLAGS = 
HPGMG_LDFLAGS = 
HPGMG_LDLIBS = -lrstream_ocr -L/opt/reservoir/latest-thenretty/rstream-3.3.3/runtime/codelet/ocr -locr -L/home/thenretty/xstack/ocr/install/x86-pthread-x86/lib
PETSC_DIR = 
PETSC_ARCH = 
PYTHON = /usr/bin/python
SRCDIR = /lustre/home/thenretty/xstack/apps/hpgmg/rocr
CONFIG_FV = y
CONFIG_TIMER_OMP = y
CONFIG_FV_CPPFLAGS = -DUSE_BICGSTAB=1 -DUSE_SUBCOMM=1 -DUSE_FCYCLES=1 -DUSE_CHEBY=1 -DSTENCIL_FUSE_DINV=1 -DSTENCIL_FUSE_BC=1
include $(SRCDIR)/base.mk
