#!/usr/bin/env bash

#-----Clean up first
rm -rf ./build ./install ./tools

##----- First make the reference output file
rm -f ./z_ref_output
echo 'INFO: ffjFinalEdt_fcn reached.' >> z_ref_output

if [ ! -s "z_ref_output" ]
then
echo "ERROR: Unusable reference output file"
exit 20
fi

#----- Create the OCR C file
python ./ptest_FORforkjoin.py > z_autogen.log
if [ ! -s "z_ptest_FORforkjoin.c" ]
then
echo "ERROR: Missing OCR C code file"
exit 30
fi

if [ "$(grep -ic ERROR z_autogen.log)" -ne 0 ]
then
echo "ERROR: Autogen generation failed."
exit 35
fi

#----- Compile and run
rm -f z_output
CONFIG_FLAGS=--guid=LABELED OCR_TYPE=x86-mpi make uninstall clean run &> z_log
grep "ffjFinalEdt_fcn" z_log | grep -v "TIME" > z_output
if [ ! -s "z_output" ]
then
echo "ERROR: Missing OCR C code output"
fi

#----- Compare
if [ "$(diff -w --brief z_ref_output z_output)" ]
then
echo "ERROR: Unit test failed."
else
echo "SUCCESS: Unit test passed."
fi

#----- Clean up
rm -f z_*
rm -rf ./build ./install ./tools
rm ../../tools/*.pyc


