MAKE := make

ifndef ARCH
  $(error Need to specify ARCH!)
endif

squeaky:
	@$(MAKE) -C $(ARCH) -f Makefile $@

configure:
	@$(MAKE) -C $(ARCH) -f Makefile $@

all:
	@$(MAKE) -C $(ARCH) -f Makefile $@

debug:
	@$(MAKE) -C $(ARCH) -f Makefile $@

check:
	@$(MAKE) -C $(ARCH) -f Makefile $@

run:
	@$(MAKE) -C $(ARCH) -f Makefile $@

install:
	@$(MAKE) -C $(ARCH) -f Makefile $@

clean:
	@$(MAKE) -C $(ARCH) -f Makefile $@

uninstall:
	@$(MAKE) -C $(ARCH) -f Makefile $@
