#!/bin/bash

files="pil.h pil.swh *.c *.swc out *.gen.c *.src.c"

for file in $files
do
	if [ -f $UHPC/pil/$file ] ; then
		rm $UHPC/pil/$file
	fi
done

for i in {0..9}
do
	for j in {0..9}
	do
		for k in {0..9}
		do
			if [ -f $UHPC/pil/example$i$j$k ] ; then
				rm $UHPC/pil/example$i$j$k
			fi
		done
	done
done

if [ -f $UHPC/pil/pilc/run.pyc ] ; then
	rm $UHPC/pil/pilc/*.pyc
fi

if ls core* 1> /dev/null 2>&1; then
	rm -f core*
fi
