#
# Master Makefile for "other" regression tests
#
# This will build the tg tree with all of the fsim variants, the
# apps tg-xe libs, and all the examples in the tg and apps trees.
#
# This should be run before attempting to execute any of the
# regression tests. It should be run with no target (or you may use
# "make all") to build everything.
#

TG_ROOT ?= $(realpath $(CURDIR)/../../../../tg/tg)
APPS_ROOT ?= $(realpath $(CURDIR)/../..)
OCR_ROOT ?= $(realpath $(CURDIR)/../../../../ocr/ocr)

all: tg-examples apps-legacy apps-examples
apps: all

tools:
	$(MAKE) -C $(TG_ROOT)
	$(MAKE) -C $(TG_ROOT)/build/build.fsim -f make-me.make install-fsim-rtlsim
	$(MAKE) -C $(TG_ROOT)/build/build.fsim -f make-me.make install-fsim-swtest

libs:
	$(MAKE) -C $(APPS_ROOT)/libs/src -f Makefile.core ARCH=tg-xe USE_TGR=yes

tg-examples:
	$(MAKE) -C $(TG_ROOT)/fsim/swtest DEBUG=1 cdemo_nonewlib
	$(MAKE) -C $(TG_ROOT)/fsim/swtest DEBUG=1 cdemo
	$(MAKE) -C $(TG_ROOT)/fsim/swtest DEBUG=1 cxxdemo
	$(MAKE) -C $(TG_ROOT)/fsim/swtest DEBUG=1 throw
	$(MAKE) -C $(TG_ROOT)/fsim/tests/rtl-asm
	$(MAKE) -C $(TG_ROOT)/fsim/tests/rtl-asm2
	$(MAKE) -C $(TG_ROOT)/fsim/tests/rtl-asm8
	$(MAKE) -C $(TG_ROOT)/xe-llvm/test/PIE fptr_simple
	$(MAKE) -C $(TG_ROOT)/xe-llvm/test/PIE multi_seg

apps-legacy:
	$(MAKE) -C $(APPS_ROOT)/legacy/tg-xe USE_TGR=yes hello
	$(MAKE) -C $(APPS_ROOT)/legacy/tg-xe USE_TGR=yes cxxhello
	$(MAKE) -C $(APPS_ROOT)/legacy/tg-xe USE_TGR=yes iotest
	$(MAKE) -C $(APPS_ROOT)/legacy/tg-xe USE_TGR=yes pthread_simple
	$(MAKE) -C $(APPS_ROOT)/legacy/tg-xe USE_TGR=yes pthread_mutex_recursive
	$(MAKE) -C $(APPS_ROOT)/legacy/tg-xe USE_TGR=yes pthread_cancel
	$(MAKE) -C $(APPS_ROOT)/legacy/tg-xe USE_TGR=yes pthread_detach
	$(MAKE) -C $(APPS_ROOT)/libs/src/libomp ARCH=tg-xe check

apps-examples:
	$(MAKE) -C $(APPS_ROOT)/examples/printf -f Makefile.tg install
	$(MAKE) -C $(APPS_ROOT)/examples/fib -f Makefile.tg install

apps-tgr-ce:
	$(MAKE) -C $(APPS_ROOT)/libs/src/libtgr/tg-ce/test c_test_1
	$(MAKE) -C $(APPS_ROOT)/libs/src/libtgr/tg-ce/test c_test_2
	$(MAKE) -C $(APPS_ROOT)/libs/src/libtgr/tg-ce/test c_test_3

apps-clean:
	$(MAKE) -C $(TG_ROOT)/fsim/swtest clean
	$(MAKE) -C $(TG_ROOT)/fsim/tests/rtl-asm clean
	$(MAKE) -C $(TG_ROOT)/fsim/tests/rtl-asm2 clean
	$(MAKE) -C $(TG_ROOT)/fsim/tests/rtl-asm8 clean
	$(MAKE) -C $(TG_ROOT)/xe-llvm/test/PIE clean
	$(MAKE) -C $(APPS_ROOT)/legacy/tg-xe clean
	$(MAKE) -C $(APPS_ROOT)/libs/src/libtgr/tg-ce/test clean
	$(MAKE) -C $(OCR_ROOT)/build squeaky
	$(MAKE) -C $(APPS_ROOT)/examples/printf -f Makefile.tg clean uninstall
	$(MAKE) -C $(APPS_ROOT)/examples/fib -f Makefile.tg clean uninstall

libs-clean:
	$(MAKE) -C $(APPS_ROOT)/libs/src -f Makefile.core ARCH=tg-xe USE_TGR=yes clean
	@rm -rf $(APPS_ROOT)/libs/install/*

tools-clean:
	$(MAKE) -C $(TG_ROOT) clean uninstall

.PHONY: all apps apps-clean libs-clean tools-clean tools libs tg-examples apps-legacy apps-examples
