# Test makefile
TARGET := $(shell basename `pwd`)

# Library root
OCXXR_LIB_ROOT ?= ../..

#################################################
# ENVIRONMENT SETUP

OCR_TYPE         ?= x86
WORKLOAD_SRC     ?= .
WORKLOAD_BUILD   ?= ./build/$(OCR_TYPE)
WORKLOAD_INSTALL ?= ./install/$(OCR_TYPE)
WORKLOAD_EXEC    ?= $(WORKLOAD_INSTALL)

# Make sure we can find OCR
ifndef XSTG_ROOT
  ifndef OCR_INSTALL_ROOT
    $(error Please define XSTG_ROOT or OCR_INSTALL_ROOT)
  endif #OCR_INSTALL_ROOT
  ifndef APPS_ROOT
    $(error Please define XSTG_ROOT or APPS_ROOT)
  endif #APPS_ROOT
else  #XSTG_ROOT
  OCR_INSTALL_ROOT ?= $(XSTG_ROOT)/ocr/ocr/install
  APPS_ROOT        ?= $(XSTG_ROOT)/apps/apps
endif #XSTG_ROOT

OCR_ROOT   ?= $(shell dirname $(OCR_INSTALL_ROOT))
OCR_LIB    ?= $(OCR_INSTALL_ROOT)/lib/libocr_$(OCR_TYPE).so


#################################################
# DEBUG / OPTIMIZATION OPTIONS

# Optimization flags
CXXFLAGS += -g -O2 -DOCR_TYPE_H=$(OCR_TYPE).h

# Enable AddressSanitizer checks
#CXX_OPTS += -g -fsanitize=address -fno-omit-frame-pointer

#################################################
# OTHER COMPILER CONFIG

CHECK_CXX_OPT_SUPPORT := echo | $(CXX) -fsyntax-only -xc++ -

# Try C++14, otherwise fall back to C++11
ifeq ($(shell $(CHECK_CXX_OPT_SUPPORT) -std=c++14 2>&1),)
CXXFLAGS += -std=c++14
else
$(info No C++14 support. Falling back to C++11.)
CXXFLAGS += -std=c++11
endif

ERROR_LIMIT := 4

# Try C++14, otherwise fall back to C++11
ifeq ($(shell $(CHECK_CXX_OPT_SUPPORT) -ferror-limit=1 2>&1),)
CXXFLAGS += -ferror-limit=$(ERROR_LIMIT) # clang
else
CXXFLAGS += -fmax-errors=$(ERROR_LIMIT) # gcc
# GCC needs this, otherwise integer format macros are missing
CXXFLAGS += -D__STDC_FORMAT_MACROS
endif

# always color the output (even when piped)
#CXXFLAGS += -fdiagnostics-color=always

#################################################
# RUN CONFIGURATION

ifndef OCR_CONFIG
OCR_CONFIG           := generated.cfg
CONFIG_NUM_THREADS   ?= 4
CONFIG_FLAGS         ?= --guid LABELED
OCR_GENERATED_CONFIG := $(WORKLOAD_INSTALL)/$(OCR_CONFIG)
endif #OCR_CONFIG

WORKLOAD_ARGS ?=
WORKLOAD_INPUT_FILE_IDX ?= 0


#################################################
# INCLUDES

# Auto-parse arguments for "make run" (WORKLOAD_ARGS)
-include $(APPS_ROOT)/makefiles/make-pre.inc


#################################################
# COMPILER FLAGS SETUP

CXX_OPTS += -pthread
LDFLAGS += -lm $(CXX_OPTS)
IFLAGS  += -I$(WORKLOAD_SRC) -I$(OCXXR_LIB_ROOT)/include -I$(OCR_INSTALL_ROOT)/include

SRCS ?= $(TARGET).cpp

CXXFLAGS += $(IFLAGS) $(OPT_FLAGS) -Wall -Wextra $(CXX_OPTS)
OBJS += $(SRCS:%.cpp=$(WORKLOAD_BUILD)/%.o)


#################################################
# MAKE TARGETS

.PHONY: all pre_build build install clean run gdb

all: build install

pre_build: $(OCR_LIB)


build: pre_build $(WORKLOAD_BUILD)/$(TARGET) $(OCR_GENERATED_CONFIG)

install: build $(WORKLOAD_INSTALL)/$(TARGET) $(WORKLOAD_INSTALL)/Makefile.$(OCR_TYPE)

ensure_dir = @mkdir -p $(@D)

# install support files
$(WORKLOAD_INSTALL)/%: $(WORKLOAD_SRC)/%
	$(ensure_dir)
	cp $< $@

# install the binary
$(WORKLOAD_INSTALL)/$(TARGET): $(WORKLOAD_BUILD)/$(TARGET)
	$(ensure_dir)
	cp $< $@

# build C++ source files
$(WORKLOAD_BUILD)/%.o: $(WORKLOAD_SRC)/%.cpp | $(OCR_LIB)
	$(ensure_dir)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# build the ocr runtime (if needed)
$(OCR_LIB):
	@echo OCR_ROOT=$(OCR_ROOT)
	@echo OCR_INSTALL_ROOT=$(OCR_INSTALL_ROOT)
	@[ -f "$(OCR_ROOT)/ocr.dox" ] \
		|| (echo "ERROR: Can't build OCR runtime (can't find OCR build directory)" && exit 1)
	OCR_TYPE=$(OCR_TYPE) make -C $(OCR_ROOT) install

ifdef OCR_GENERATED_CONFIG
$(OCR_GENERATED_CONFIG):
	$(ensure_dir)
	$(OCR_ROOT)/scripts/Configs/config-generator.py $(CONFIG_FLAGS) --threads $(CONFIG_NUM_THREADS) --remove-destination --output $@
endif #OCR_GENERATED_CONFIG

# link the binary
$(WORKLOAD_BUILD)/$(TARGET): $(OBJS) $(OCR_LIB)
	$(ensure_dir)
	$(CXX) -o $@ $^ $(LDFLAGS)

# delete build and install directories
clean:
	rm -rf $(WORKLOAD_BUILD) $(WORKLOAD_INSTALL)

# run the binary
run: install
	cd $(WORKLOAD_EXEC) && \
	OCR_CONFIG=$(OCR_CONFIG) \
	$(RUN_TOOL) ./$(TARGET) $(WORKLOAD_ARGS)

# run the binary with gdb
gdb: RUN_TOOL := gdb -ex r --args
gdb: run
