all:
	$(MAKE) -C ./utils
	$(MAKE) -C ./small
	$(MAKE) -C ./large

run:
	$(MAKE) -C ./small run
	$(MAKE) -C ./large run

clean:
	$(MAKE) -C ./utils clean
	$(MAKE) -C ./small clean
	$(MAKE) -C ./large clean
