# This file is subject to the license agreement located in the file LICENSE
# and cannot be distributed without it. This notice cannot be
# removed or modified.
#ifndef APPS_ROOT
#$(warning APPS_ROOT not set. Using default path. APPS_ROOT can also be set by sourcing app_env.bash from "apps/"!)
APPS_ROOT ?= $(XSTG_ROOT)/apps/apps
#endif
OCR_REPO_TOP ?= $(XSTG_ROOT)/ocr
APPS_REPO_TOP ?= $(XSTG_ROOT)/apps

# ARCH
ARCH            = x86

# APPS
APPS_ROOT       ?= ${APPS_REPO_TOP}/apps
APPS_LIBS_ROOT  ?= ${APPS_REPO_TOP}/apps/libs/install/x86


# OCR_TYPE
OCR_TYPE        ?= x86

# OCR
OCR_TARGET       ?= x86
OCR_INSTALL_ROOT ?= ${OCR_REPO_TOP}/ocr/install
OCR_ROOT         ?= ${OCR_REPO_TOP}/ocr
OCR_BUILD_ROOT   ?= ${OCR_REPO_TOP}/ocr/build

# APPLICATION
WORKLOAD_SRC          ?= .
WORKLOAD_BUILD_ROOT   ?= ./build
WORKLOAD_INSTALL_ROOT ?= ./install

# Specific Tempest requirements
TEMPESTBASEDIR := $(WORKLOAD_SRC)/../../

# Cannonicalize the tempest paths
TEMPESTBASEDIR := $(shell cd "${TEMPESTBASEDIR}" && pwd)
TEMPESTLIBS    := $(TEMPESTBASEDIR)/lib

# If 0, the workload has no input file
# If 1+, this is the index in the argument
# list after which everything is considered an
# input file. Note that the index STARTS AT 1
WORKLOAD_INPUT_FILE_IDX := 0

# You can specify default arguments here. These
# will be overriden by (in order):
#   - the WORKLOAD_ARGS environment variable
#   - the arguments passed to 'make run'
# To restate, the arguments passed to make run have
# the highest priority and will override both the
# default arguments here and the ones passed through
# an environment variable
WORKLOAD_ARGS ?=

# Run mode (not fully supported)
# Set to "yes" if running with torque
RUN_TORQUE ?= no
# Set to "yes" if Jenkins is running this job as an automated test
RUN_JENKINS ?= no
# Set to yes if running visualizer or export as environment variable
ENABLE_VISUALIZER ?= no
## END of variables coming from user/environment

RUN_MODE := buildApp

include ${APPS_ROOT}/makefiles/make-pre.inc

# Name of the application to build
#TARGET := DataContainerDbAlloc
TARGET := DataContainerDbAlloc

#DataContainerTest: $(TEMPESTLIBS)/libhardcoreatm.a $(TEMPESTLIBS)/libtempestbase.a

# Space separated list of directory names in apps/libs/src
# that need to be built. These will be built for ARCH

# Space separated list of source files

SRCS :=  $(TARGET).cpp ../ocr-dballoc/src/ocr_db_alloc.cpp
CONFIG_FLAGS := --guid LABELED
OBJS := $(notdir $(SRCS:.cpp=.o))
CFLAGS += -std=c++14 -DUSE_OCR -I${TEMPESTBASEDIR}/include
CFLAGS += -I../ocr-dballoc/include -I$(OCXXR_LIB_ROOT)/include
CFLAGS += -DUSE_OCR_TEST
LDFLAGS := -lpthread -lm -L$(TEMPESTLIBS) -lhardcoreatm -ltempestbase  -locr_$(OCR_TYPE) -lnetcdf -lnetcdf_c++ -llapack -lblas

# Targets:
#   - all:     Build the application.
#   - debug:   Build the debug version of the application
#   - install: Build and install
#   - run:     Run the application
all:	CFLAGS += -O3
all:	TARGETS := all
all:	default

debug:	CFLAGS += -g -O0 -fno-inline
debug:	TARGETS := debug
debug:	default

install: all

prebuild:
	APPS_ROOT=$(APPS_ROOT) OCR_INSTALL_ROOT=$(OCR_INSTALL_ROOT) TEMPESTBASEDIR=$(TEMPESTBASEDIR) \
	  $(MAKE) -C $(TEMPESTBASEDIR)/src/base
	APPS_ROOT=$(APPS_ROOT) OCR_INSTALL_ROOT=$(OCR_INSTALL_ROOT) TEMPESTBASEDIR=$(TEMPESTBASEDIR) \
	  $(MAKE) -C $(TEMPESTBASEDIR)/src/atm

# This rule will be executed prior to execution:
#  - For the FSim target, this happens when the binary is built
#  - For all other targets this happens prior to running the
#    executable
# WORKLOAD_ARGS and WORKLOAD_INPUTS are available
# to you and contain, respectively, the non file
# arguments and the file arguments. They will be
# passed directly to the application unless you
# modify them. You can use the following
# syntax to do so:
# $(eval WORKLOAD_INPUTS := something) or
# $(eval WORKLOAD_INPUTS := $(shell <script>))
# The second syntax will execute <script> and assign
# its output to WORKLOAD_INPUTS
#
# You may also want to assign a value to WORKLOAD_OUTS
# which should contain the list of output files produced
# by the application (to be passed to postrun). This is
# taken-care of for you on FSim but not on any of the
# other platforms.
# 'prerun: ;' is an empty rule (the rule is required)
.PHONY: prerun
prerun: ;

# This rule will be executed after execution
# The variable ${WORKLOAD_OUTS} contains a space separated
# list of output files
# 'postrun: ;' is an empty rule (the rule is required
# to be present though)
.PHONY: postrun
postrun: ;

# Include common part
include ${APPS_ROOT}/makefiles/make-inc.inc

# Use g++ and not gcc
#CC := g++
CC := clang++
#CC := mpicxx
