OCR_INSTALL="$HOME/ocr_install_mpiicc_redevt-nodebug"
BASECPGN=${BASECPGN-"xp-benchmark-hpcgEagerRedlib-wrank"}

TPLARG_QUEUE=XAS iter=50 TARGET_NAME=hpcgEagerRedlibReg CPGN=${BASECPGN}-regular NO_DEBUG=yes OCR_INSTALL=${OCR_INSTALL} CFLAGS="-DCONSECUTIVE_PLACEMENT -DRANK_TIMER -DRANK_TIMER_ITONE" ./scripts/experiments.sh $@
TPLARG_QUEUE=XAS iter=50 TARGET_NAME=hpcgEagerRedlibNoRed CPGN=${BASECPGN}-noreduction NO_DEBUG=yes OCR_INSTALL=${OCR_INSTALL} CFLAGS="-DCONSECUTIVE_PLACEMENT -DRANK_TIMER -DRANK_TIMER_ITONE -DNO_REDUCTION" ./scripts/experiments.sh $@
TPLARG_QUEUE=XAS iter=50 TARGET_NAME=hpcgEagerRedlibNoRedNoMg CPGN=${BASECPGN}-noreduction-nomg NO_DEBUG=yes OCR_INSTALL=${OCR_INSTALL} CFLAGS="-DCONSECUTIVE_PLACEMENT -DRANK_TIMER -DRANK_TIMER_ITONE -DNO_REDUCTION -DNO_MG" ./scripts/experiments.sh $@
TPLARG_QUEUE=XAS iter=50 TARGET_NAME=hpcgEagerRedlibNoMgNoHalo CPGN=${BASECPGN}-nomg-nohalo NO_DEBUG=yes OCR_INSTALL=${OCR_INSTALL} CFLAGS="-DCONSECUTIVE_PLACEMENT -DRANK_TIMER -DRANK_TIMER_ITONE -DNO_MG -DNO_HALO_HPCG" ./scripts/experiments.sh $@
TPLARG_QUEUE=XAS iter=50 TARGET_NAME=hpcgEagerRedlibNoRedNoMgNoHalo CPGN=${BASECPGN}-noreduction-nomg-nohalo NO_DEBUG=yes OCR_INSTALL=${OCR_INSTALL} CFLAGS="-DCONSECUTIVE_PLACEMENT -DRANK_TIMER -DRANK_TIMER_ITONE -DNO_REDUCTION -DNO_MG -DNO_HALO_HPCG" ./scripts/experiments.sh $@
