# This file is subject to the license agreement located in the file LICENSE
# and cannot be distributed without it. This notice cannot be
# removed or modified.

ifdef RESULTS_LOG
	OUTPUT = >> $(RESULTS_LOG)
else
	OUTPUT = ""
endif
