#!/bin/bash
# Nek5000 build config file
# (c) 2008,2009,2010 UCHICAGO ARGONNE, LLC

# source path
SOURCE_ROOT="../../src/"

# Fortran compiler
#original F77="mpixlf77_r -qsmp=omp -qnosave"
F77="mpiifort"
#F77="mpiifort -openmp"
#F77="mpifort -fopenmp"

# C compiler
#original CC="mpixlc_r -qsmp=omp"
CC="mpiicc"
#CC="mpiicc -openmp"
#CC="mpicc -fopenmp"

# pre-processor symbol list
# (set PPLIST=? to get a list of available symbols)
#PPLIST="TIMERS"

TargetARCH=Nothing0
#TargetARCH=SNB

if [ ${TargetARCH} == 'SNB' ]; then
GFLAGS=-xAVX
fi

if [ ${TargetARCH} == 'Nothing0' ]; then
GFLAGS=""
fi


# OPTIONAL SETTINGS
# -----------------

# enable MPI (default true)
#IFMPI="false"

# auxilliary files to compile
# NOTE: source files have to located in the same directory as makenek
#       a makefile_usr.inc has to be provided containing the build rules
#USR="foo.o"

# linking flags
USR_LFLAGS=""
#USR_LFLAGS="-L/usr/lib/ -lfoo"

# generic compiler flags
VECREPORT=""
#VECREPORT="-opt-report"
#VECREPORT="-qopt-report"
#VECREPORT="-vec-report6"
#VECREPORT="-qopt-report=5 -qopt-report-phase=vec -qopt-report-file=z_opt-report.log"

G=""
#G="-g"
#G="-g -debug inline-debug-info ${GFLAGS} ${VECREPORT}"
#G="${GFLAGS} ${VECREPORT}"
#G="${GFLAGS} -opt-report"

# optimization flags
OPT_FLAGS_STD="-O3"
#OPT_FLAGS_STD="-O0"
OPT_FLAGS_MAG=${OPT_FLAGS_STD}

export OMP_NUM_THREADS=2

###############################################################################
# DONT'T TOUCH WHAT FOLLOWS !!!
###############################################################################
# assign version tag
mver=1
# overwrite source path with optional 2nd argument
if [ -d $2 ] && [ $# -eq 2 ]; then
  SOURCE_ROOT="$2"
  echo "change source code directory to: ", $SOURCE_ROOT
fi
# do some checks and create makefile
source $SOURCE_ROOT/makenek.inc
# compile
make -j4 -f makefile 2>&1 | tee compiler.out
#ITL original--> exit 0
