#!/bin/bash
export OCR_INSTALL=$HOME/xstack/ocr/install/x86-pthread-x86
export OCR_TYPE=x86-pthread-x86
. $HOME/xstack/hll/cnc-ocr/setup_env.sh
export CNCOCR_INSTALL=$HOME/xstack/hll/cnc-ocr
export PATH=$PATH:$CNCOCR_INSTALL/bin
which cncocr_t
cncocr_t Stencil1D.cnc
export OCR_CONFIG=$OCR_INSTALL/config/default.cfg
#make clean
make
