HPGMG_ARCH = build-modern
HPGMG_CC = mpiicc
HPGMG_CFLAGS = -g -O3 -openmp -fp-model precise
HPGMG_CPPFLAGS =
HPGMG_LDFLAGS =
HPGMG_LDLIBS =
PETSC_DIR =
PETSC_ARCH =
PYTHON = /usr/bin/python
SRCDIR = /lustre/home/gjost/xstack_checkin/apps/hpgmg-0.1/mpi-omp
CONFIG_FV = y
CONFIG_FV_CPPFLAGS = -DUSE_MPI=1 -DUSE_BICGSTAB=1 -DUSE_SUBCOMM=1 -DUSE_VCYCLES=1 -DUSE_GSRB=1 -DSTENCIL_FUSE_BC=1
include $(SRCDIR)/base.mk
