# Definitions for ROSE Tools


SHELL=/bin/bash
CC=gcc
CXX=g++
RM = rm -f

TOOL_INC=-I$(ROSE_INS)/include/rose  -I$(BOOST_INS)/include

TOOL_LNK=$(ROSE_INS)/lib/librose.so -L$(BOOST_INS)/lib -lboost_date_time -lboost_thread -lboost_filesystem -lboost_program_options -lboost_regex -lboost_system -lboost_wave -lboost_iostreams $(ROSE_INS)/lib/libhpdf.so -Wl,-rpath -Wl,$(ROSE_INS)/lib -Wl,-rpath -Wl,$(ROSE_INS)/lib

#TOOL_LNK=$(ROSE_INS)/lib/librose.so -L$(BOOST_INS)/lib -ldl -lboost_date_time -lboost_thread -lboost_filesystem -lboost_program_options -lboost_regex -lboost_system -lboost_wave -lboost_iostreams $(ROSE_INS)/lib/libhpdf.so -lm -pthread -Wl,-rpath -Wl,$(ROSE_INS)/lib -Wl,-rpath -Wl,$(ROSE_INS)/lib


CFLAGS=-D__leaf__=__externally_visible__
CXXFLAGS=
CC_INC=-I.


MPI_VERSION=../../../../../../../apps/libs/x86
MPICC = $(CC)
MPI_FLAGS=-I$(MPI_VERSION)/include -D__leaf__=__externally_visible__ -L$(MPI_VERSION)/lib/release -L$(MPI_VERSION)/lib -lmpifort -lmpi -lmpigi -ldl -lrt -lpthread -lgcc

#MPI_VERSION=/opt/intel/tools//impi/5.0.1.035/intel64
#MPICC = mpicc
#MPIRUN = mpirun
#MPI_FLAGS=-I$(MPI_VERSION)/include -D__leaf__=__externally_visible__ -L$(MPI_VERSION)/lib/release -L$(MPI_VERSION)/lib -lmpifort -lmpi -lmpigi -ldl -lrt -lpthread -lgcc

ZGRVIEW=java -jar /opt/ZGRViewer-0.8.2/zgrviewer/target/zgrviewer-0.8.2.jar
