# This file is subject to the license agreement located in the file LICENSE
# and cannot be distributed without it. This notice cannot be
# removed or modified.

OCR_TYPE := tg-x86

TOP := $(dir $(lastword $(MAKEFILE_LIST)))
include $(TOP)/Makefile.x86-base
