#!/usr/bin/env bash

#----- First make the reference output file
rm -f ./z_ref_output
echo "TESTIO> sum = 55" > z_ref_output

if [ ! -s "z_ref_output" ]
then
echo "ERROR: Unusable reference output file"
exit 20
fi

#----- Create the OCR C file
python ./utest_labelEdt.py > z_autogen.log
if [ ! -s "z_utest_labeledt.c" ]
then
echo "ERROR: Missing OCR C code file"
exit 30
fi

if [ "$(grep -ic ERROR z_autogen.log)" -ne 0 ]
then
echo "ERROR: Autogen generation failed."
exit 35
fi

#----- Compile and run
rm -f z_output
CONFIG_FLAGS=--guid=LABELED OCR_TYPE=x86 make run > z_log; grep "TESTIO>" z_log > z_output
if [ ! -s "z_output" ]
then
echo "ERROR: Missing OCR C code output"
exit 40
fi

#----- Compare
if [ "$(diff -w --brief z_ref_output z_output)" ]
then
echo "ERROR: Black box test failed."
exit 50
else
echo "SUCCESS: Black box test passed."
fi

#----- Clean up
rm -f z_*
rm -rf ./build ./install ./tools
rm ../../tools/*.pyc


