# Definitions for ROSE Tools


SHELL=/bin/bash

# Jenkins needs to have the ROSE area defined.
ROSE_INS ?= /home/saananth/local/rose
BOOST_INS ?= /opt/boost_1_46_1/installTree

ROSE_INC=-I$(ROSE_INS)/include/rose  -I$(BOOST_INS)/include

ROSE_LNK=$(ROSE_INS)/lib/librose.so -L$(BOOST_INS)/lib -lboost_date_time -lboost_thread -lboost_filesystem -lboost_program_options -lboost_regex -lboost_system -lboost_wave -lboost_iostreams $(ROSE_INS)/lib/libhpdf.so -Wl,-rpath -Wl,$(ROSE_INS)/lib -Wl,-rpath -Wl,$(ROSE_INS)/lib -Wl,-rpath -Wl,$(BOOST_INS)/lib