language: cpp
sudo: required
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  - CC_FLAGS=
  - CC_FLAGS="-DPRIVILEGE_CHECKS -DBOUNDS_CHECKS"
  - CC_FLAGS=-DLEGION_SPY
  - CC_FLAGS=-std=c++0x
matrix:
  exclude:
    - os: osx
      compiler: gcc
# blacklist some branches
branches:
  except:
    - deppart
    - rdir
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#       - llvm-toolchain-precise-3.5
#     packages:
#       - g++-4.9
#       - clang-3.5
#       - libclang-3.5-dev
#       - llvm-3.5-dev
before_install:
  - |
    if [ "$(uname)" = "Linux" ]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      # sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' >> /etc/apt/sources.list"
      # wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo sh -c "echo 'deb http://legion.stanford.edu/~eslaught/llvm-deb-mirror/apt/precise/ llvm-toolchain-precise-3.5 main' >> /etc/apt/sources.list"
      wget -O - http://legion.stanford.edu/~eslaught/llvm-deb-mirror/apt/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo apt-get update -qq
      sudo apt-get install -qq g++-4.9 clang-3.5 libclang-3.5-dev llvm-3.5-dev
    fi
  - if [ "$(uname)" = "Linux" -a "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$(uname)" = "Linux" -a "$CXX" = "clang++" ]; then export CXX="clang++-3.5" CC="clang-3.5"; fi
  - if [ "$(uname)" = "Linux" ]; then export LLVM_CONFIG="llvm-config-3.5"; fi
  - export TERRA_CXX="$CXX"
  - export TERRA_CC="$CC"
  - export TERRA_LINK="$CXX"
script:
  - ./language/travis.py
  - make -C test/realm LG_RT_DIR=../../runtime DEBUG=0 SHARED_LOWLEVEL=1 run_all
  - make -C test/realm LG_RT_DIR=../../runtime DEBUG=0 SHARED_LOWLEVEL=1 clean
  - make -C test/realm LG_RT_DIR=../../runtime DEBUG=0 SHARED_LOWLEVEL=0 USE_CUDA=0 USE_GASNET=0 run_all
