# Test makefile
TARGET := VectorTest

# Library root
OCR_ALLOC_LIB_ROOT ?= ../..

#################################################
# DEBUG / OPTIMIZATION OPTIONS

# Optimization flags
CXXFLAGS += -std=gnu++11 -g -O2

# Enable AddressSanitizer checks
#CXX_OPTS += -g -fsanitize=address -fno-omit-frame-pointer


#################################################
# ENVIRONMENT SETUP

OCR_TYPE         ?= x86
WORKLOAD_SRC     ?= .
WORKLOAD_BUILD   ?= ./build/$(OCR_TYPE)
WORKLOAD_INSTALL ?= ./install/$(OCR_TYPE)
WORKLOAD_EXEC    ?= $(WORKLOAD_INSTALL)

# Make sure we can find OCR and CnC-OCR
ifndef XSTACK_ROOT
  ifndef OCR_INSTALL_ROOT
    $(error Please define XSTACK_ROOT or OCR_INSTALL_ROOT)
  endif #OCR_INSTALL_ROOT
  ifndef APPS_ROOT
    $(error Please define XSTACK_ROOT or APPS_ROOT)
  endif #APPS_ROOT
else  #XSTACK_ROOT
  OCR_INSTALL_ROOT ?= $(XSTACK_ROOT)/ocr/install
  APPS_ROOT        ?= $(XSTACK_ROOT)/apps
endif #XSTACK_ROOT

OCR_ROOT   ?= $(shell dirname $(OCR_INSTALL_ROOT))
OCR_AR     ?= $(OCR_INSTALL_ROOT)/$(OCR_TYPE)/lib/libocr.a


#################################################
# RUN CONFIGURATION

ifndef OCR_CONFIG
OCR_CONFIG           := generated.cfg
CONFIG_NUM_THREADS   ?= 4
OCR_GENERATED_CONFIG := $(WORKLOAD_INSTALL)/$(OCR_CONFIG)
endif #OCR_CONFIG

WORKLOAD_ARGS ?=
WORKLOAD_INPUT_FILE_IDX ?= 0


#################################################
# INCLUDES

# Auto-parse arguments for "make run" (WORKLOAD_ARGS)
-include $(APPS_ROOT)/makefiles/make-pre.inc


#################################################
# COMPILER FLAGS SETUP

CXX_OPTS += -pthread
LDFLAGS += -lm $(CXX_OPTS)
IFLAGS  += -I$(WORKLOAD_SRC) -I$(OCR_ALLOC_LIB_ROOT)/include -I$(OCR_INSTALL_ROOT)/$(OCR_TYPE)/include

SRCS := $(TARGET).cpp $(OCR_ALLOC_LIB_ROOT)/src/ocr_db_alloc.cpp

CXXFLAGS += $(IFLAGS) $(OPT_FLAGS) -Wall $(CXX_OPTS)
OBJS += $(SRCS:%.cpp=$(WORKLOAD_BUILD)/%.o)


#################################################
# MAKE TARGETS

.PHONY: all pre_build build install clean run gdb

all: build install

pre_build: $(OCR_AR)


build: pre_build $(WORKLOAD_BUILD)/$(TARGET) $(OCR_GENERATED_CONFIG)

install: build $(WORKLOAD_INSTALL)/$(TARGET) $(WORKLOAD_INSTALL)/Makefile.$(OCR_TYPE)

ensure_dir = @mkdir -p $(@D)

# install support files
$(WORKLOAD_INSTALL)/%: $(WORKLOAD_SRC)/%
	$(ensure_dir)
	cp $< $@

# install the binary
$(WORKLOAD_INSTALL)/$(TARGET): $(WORKLOAD_BUILD)/$(TARGET)
	$(ensure_dir)
	cp $< $@

# build C source files
$(WORKLOAD_BUILD)/%.o: $(WORKLOAD_SRC)/%.cpp | $(OCR_AR)
	$(ensure_dir)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# build the ocr runtime (if needed)
$(OCR_AR):
	@echo OCR_ROOT=$(OCR_ROOT)
	@echo OCR_INSTALL_ROOT=$(OCR_INSTALL_ROOT)
	@[ -f "$(OCR_ROOT)/ocr.dox" ] \
		|| (echo "ERROR: Can't build OCR runtime (can't find OCR build directory)" && exit 1)
	OCR_TYPE=$(OCR_TYPE) make -C $(OCR_ROOT) install

ifdef OCR_GENERATED_CONFIG
$(OCR_GENERATED_CONFIG):
	$(ensure_dir)
	$(OCR_ROOT)/scripts/Configs/config-generator.py $(CONFIG_FLAGS) --threads $(CONFIG_NUM_THREADS) --remove-destination --output $@
endif #OCR_GENERATED_CONFIG

# link the binary
$(WORKLOAD_BUILD)/$(TARGET): $(OBJS) $(OCR_AR)
	$(ensure_dir)
	$(CXX) -o $@ $^ $(LDFLAGS)

# delete build and install directories
clean:
	rm -rf $(WORKLOAD_BUILD) $(WORKLOAD_INSTALL)

# run the binary
run: install
	cd $(WORKLOAD_EXEC) && \
	OCR_CONFIG=$(OCR_CONFIG) \
	$(RUN_TOOL) ./$(TARGET) $(WORKLOAD_ARGS)

# run the binary with gdb
gdb: RUN_TOOL := gdb -ex r --args
gdb: run
