#!/bin/bash -l
#SBATCH -p regular
#SBATCH -N 8
#SBATCH -t 00:010:00
#SBATCH -J z_nekbone_inOcr
#SBATCH -o zz_z_log%j
#SBATCH -L SCRATCH

# Setup for intel MPI
module load impi/5.1.1.109
export MPI_ROOT=/opt/intel/parallel_studio_xe_2016.0.047/compilers_and_libraries_2016/linux/mpi/intel64
export PATH=${MPI_ROOT}/bin:$PATH
export LD_LIBRARY_PATH=${MPI_ROOT}/lib:$LD_LIBRARY_PATH

# Setup OCR
export OCR_TYPE=x86-mpi
export CONFIG_NUM_THREADS=9   # ThreadCount + 1 for OCR
export OCR_NUM_NODES=${SLURM_JOB_NUM_NODES} # matches the -N parameter
#   export CC=mpicc
export CC=mpiicc
export NO_DEBUG=yes
export OCRRUN_OPT_ENVKIND=SLURM

# Make & Run
cd $SLURM_SUBMIT_DIR
export RUN_TOOL=/usr/bin/time
export RUN_MODE=buildApp
make -f Makefile.x86-mpi run WORKLOAD_ARGS="4 4 4 2 2 2 8 100"

echo "M^3=N=8 (Rx,Ry,Rz)=(4,4,4) (Ex,Ey,Ez)=(2,2,2) pDOF=8 CGcount=100"
